import {
    currentModulePath, packageNameOf, patch, findFile
} from '@tech_query/node-toolkit';

import {
    ensureDirSync, copy, readdirSync, readJSON, writeJSON, existsSync,
    removeSync, moveSync, outputFile
} from 'fs-extra';

import { join, extname } from 'path';

import Git from 'simple-git/promise';

import config from '../package.json';


const _base_ = join(currentModulePath(), '../../');

/**
 * @private
 *
 * @type {Object}
 */
export  const _meta_ = JSON.parse( config );


/**
 * @param {String}     path     - Local folder
 * @param {String|URL} [remote] - Git URL of a Remote repository
 *
 * @return {SimpleGit}
 */
export  async function bootGit(path, remote) {

    ensureDirSync( path );

    const git = Git( path );

    if (! (await git.checkIsRepo()))  await git.init();

    if (! (await git.getRemotes())[0]) {

        if (! remote) {

            const package_name = packageNameOf( path ),
                userID = await git.raw(['config', '--get', 'user.name']);

            remote = `https://github.com/${userID.trim()}/${package_name}.git`;
        }

        await git.addRemote('origin', remote);
    }

    return git;
}


/**
 * @param {String}   template - Path relative from `process.cwd()`
 * @param {String}   dist     - Path relative from `process.cwd()`
 * @param {Function} [filter]
 */
export  async function copyFrom(template, dist, filter) {

    await copy(template,  dist,  {overwrite: false, filter});

    const setting = readdirSync( template )
        .filter(file  =>  extname(file) === '.json');

    for (let file of setting) {

        const source = join(template, file), target = join(dist, file);

        await writeJSON(
            target,
            patch(await readJSON( target ),  await readJSON( source )),
            {spaces: 4}
        );
    }
}


function fixIgnore(name,  path = '.') {

    const ignore_0 = join(path, `.${name}ignore`),
        ignore_1 = join(path, `${name}ignore`);

    if (existsSync( ignore_0 ))
        removeSync( ignore_1 );
    else
        moveSync(ignore_1, ignore_0);
}


/**
 * @this {Object}
 *
 * @param {String}    path  - Project root
 * @param {SimpleGit} git
 * @param {?Boolean}  win32
 *
 * @example
 *     setReadMe.call(packageJSON, '/home/test/example', git)
 */
export  async function setReadMe(path, git, win32) {

    const repo = /([^/]+\/[^/]+)\.git$/.exec(
        (await git.getRemotes( true ))[0].refs.push
    )[1];

    await outputFile(
        join(path, 'ReadMe.md'),
        `# ${packageNameOf( path )}

Project generated by [${this.name}](${this.homepage})

[![NPM Dependency](https://david-dm.org/${repo}.svg)](https://david-dm.org/${repo})

${win32 ? '' : `[![Build Status](https://travis-ci.com/${repo}.svg?branch=master)](https://travis-ci.com/${repo})`}`
    );
}


/**
 * @param {String}    path  - Project root
 * @param {SimpleGit} git
 *
 * @return {Object}
 * @property {String} path - Path of `package.json`
 * @property {Object} meta - Data of `package.json`
 */
export  async function setAuthor(path, git) {

    path = join(path, 'package.json');

    const meta = await readJSON( path );

    meta.author = (await git.raw(['config', '--get', 'user.email'])).trim();

    return  {path, meta};
}


/**
 * @param {String}    path        - Project root
 * @param {SimpleGit} git         - Git repository instance of `path`
 * @param {String[]}  [system=[]] - https://docs.npmjs.com/files/package.json#os
 *
 * @return {Object} `package.json` data
 */
export  async function setRoot(path,  git,  system = []) {

    await copyFrom(join(_base_, 'template'),  path);

    fixIgnore('git', path),  fixIgnore('npm', path);

    const win32 = (system[0] === 'win32'),  config = await setAuthor(path, git);

    if (! findFile(/ReadMe(\.(md|markdown))?/i, path))
        await setReadMe.call(_meta_, path, git, win32);

    if ( system[0] )  config.meta.os = system;

    removeSync( join(path,  `${win32 ? '.travis' : 'azure-pipelines'}.yml`) );

    await writeJSON(config.path,  config.meta,  {spaces: 4});

    return config.meta;
}
