import {
    packageOf, currentModulePath, packageNameOf, patch, findFile
} from '@tech_query/node-toolkit';

import {
    ensureDirSync, copy, readdirSync, readJSON, writeJSON, existsSync,
    removeSync, moveSync, outputFile
} from 'fs-extra';

import { join, extname } from 'path';

import Git from 'simple-git/promise';


/**
 * @type {Object}
 */
export  const creator_meta = packageOf( currentModulePath() );


/**
 * @param {String}     path     - Local folder
 * @param {String|URL} [remote] - Git URL of a Remote repository
 *
 * @return {SimpleGit}
 */
export  async function bootGit(path, remote) {

    ensureDirSync( path );

    const git = Git( path );

    if (! (await git.checkIsRepo()))  await git.init();

    if (! (await git.getRemotes())[0]) {

        if (! remote) {

            const package_name = packageNameOf( path ),
                userID = await git.raw(['config', '--get', 'user.name']);

            remote = `https://github.com/${userID.trim()}/${package_name}.git`;
        }

        await git.addRemote('origin', remote);
    }

    return git;
}


/**
 * @param {String}   template - Path relative from this package
 * @param {String}   dist     - Path relative from `process.cwd()`
 * @param {Function} [filter]
 */
export  async function copyFrom(template, dist, filter) {

    template = join(creator_meta.path, template);

    await copy(template,  dist,  {overwrite: false, filter});

    const setting = readdirSync( template )
        .filter(file  =>  extname(file) === '.json');

    for (let file of setting) {

        const source = join(template, file), target = join(dist, file);

        await writeJSON(
            target,
            patch(await readJSON( target ),  await readJSON( source )),
            {spaces: 4}
        );
    }
}


function fixIgnore(name,  path = '.') {

    const ignore_0 = join(path, `.${name}ignore`),
        ignore_1 = join(path, `${name}ignore`);

    if (existsSync( ignore_0 ))
        removeSync( ignore_1 );
    else
        moveSync(ignore_1, ignore_0);
}

async function setReadMe(path, git, win32) {

    const repo = /([^/]+\/[^/]+)\.git$/.exec(
        (await git.getRemotes( true ))[0].refs.push
    )[1];

    await outputFile(
        join(path, 'ReadMe.md'),
        `# ${packageNameOf( path )}

Project generated by [${creator_meta.meta.name}](${creator_meta.meta.homepage})

[![NPM Dependency](https://david-dm.org/${repo}.svg)](https://david-dm.org/${repo})

${win32 ? '' : `[![Build Status](https://travis-ci.com/${repo}.svg?branch=master)](https://travis-ci.com/${repo})`}`
    );
}

/**
 * @param {String}    path        - Project root
 * @param {SimpleGit} git         - Git repository instance of `path`
 * @param {String[]}  [system=[]] - https://docs.npmjs.com/files/package.json#os
 *
 * @return {Object} `package.json` data
 */
export  async function setRoot(path,  git,  system = []) {

    await copyFrom('./template', path);

    fixIgnore('git', path),  fixIgnore('npm', path);

    const win32 = (system[0] === 'win32');

    if (! findFile(/ReadMe(\.(md|markdown))?/i, path))
        await setReadMe(path, git, win32);

    const config = join(path, 'package.json');

    const meta = await readJSON( config );

    meta.author = (await git.raw(['config', '--get', 'user.email'])).trim();

    if ( system[0] )  meta.os = system;

    removeSync( join(path,  `${win32 ? '.travis' : 'azure-pipelines'}.yml`) );

    await writeJSON(config,  meta,  {spaces: 4});

    return meta;
}
